<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Applied Econometrics Notes - 3&nbsp; The Multiple Regression Model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./assumptions.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./multiple.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Multiple Regression Model</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Applied Econometrics Notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Simple Regression Model: Basics of OLS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Classical Linear Model (Gauss-Markov) Assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Multiple Regression Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-trivariate-model-interpretation" id="toc-the-trivariate-model-interpretation" class="nav-link active" data-scroll-target="#the-trivariate-model-interpretation"><span class="header-section-number">3.1</span> The Trivariate Model &amp; Interpretation</a></li>
  <li><a href="#the-ols-estimators-and-normal-equations" id="toc-the-ols-estimators-and-normal-equations" class="nav-link" data-scroll-target="#the-ols-estimators-and-normal-equations"><span class="header-section-number">3.2</span> The OLS Estimators and Normal Equations</a>
  <ul class="collapse">
  <li><a href="#extending-the-mtcars-model" id="toc-extending-the-mtcars-model" class="nav-link" data-scroll-target="#extending-the-mtcars-model"><span class="header-section-number">3.2.1</span> Extending the <code>mtcars</code> Model</a></li>
  </ul></li>
  <li><a href="#standard-errors-of-the-ols-estimates" id="toc-standard-errors-of-the-ols-estimates" class="nav-link" data-scroll-target="#standard-errors-of-the-ols-estimates"><span class="header-section-number">3.3</span> Standard Errors of the OLS Estimates</a></li>
  <li><a href="#r-squared-and-the-adjusted-r-squared" id="toc-r-squared-and-the-adjusted-r-squared" class="nav-link" data-scroll-target="#r-squared-and-the-adjusted-r-squared"><span class="header-section-number">3.4</span> R-squared and The Adjusted R-squared</a>
  <ul class="collapse">
  <li><a href="#interpreting-r2-and-barr2-in-practice" id="toc-interpreting-r2-and-barr2-in-practice" class="nav-link" data-scroll-target="#interpreting-r2-and-barr2-in-practice"><span class="header-section-number">3.4.1</span> Interpreting <span class="math inline">\(R^2\)</span> and <span class="math inline">\(\bar{R}^2\)</span> in Practice</a></li>
  </ul></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing"><span class="header-section-number">3.5</span> Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#testing-individual-coefficients" id="toc-testing-individual-coefficients" class="nav-link" data-scroll-target="#testing-individual-coefficients"><span class="header-section-number">3.5.1</span> Testing Individual Coefficients</a></li>
  <li><a href="#testing-the-overall-significance-the-f-test" id="toc-testing-the-overall-significance-the-f-test" class="nav-link" data-scroll-target="#testing-the-overall-significance-the-f-test"><span class="header-section-number">3.5.2</span> Testing the Overall Significance: The F-Test</a></li>
  <li><a href="#joint-tests-and-restricted-models" id="toc-joint-tests-and-restricted-models" class="nav-link" data-scroll-target="#joint-tests-and-restricted-models"><span class="header-section-number">3.5.3</span> Joint Tests and Restricted Models</a></li>
  </ul></li>
  <li><a href="#the-problem-of-omitted-variable-bias" id="toc-the-problem-of-omitted-variable-bias" class="nav-link" data-scroll-target="#the-problem-of-omitted-variable-bias"><span class="header-section-number">3.6</span> The Problem of Omitted Variable Bias</a>
  <ul class="collapse">
  <li><a href="#direction-of-the-bias" id="toc-direction-of-the-bias" class="nav-link" data-scroll-target="#direction-of-the-bias"><span class="header-section-number">3.6.1</span> Direction of the Bias</a></li>
  </ul></li>
  <li><a href="#the-cost-of-including-an-irrelevant-variable" id="toc-the-cost-of-including-an-irrelevant-variable" class="nav-link" data-scroll-target="#the-cost-of-including-an-irrelevant-variable"><span class="header-section-number">3.7</span> The Cost of Including an Irrelevant Variable</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Multiple Regression Model</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The simple regression model is powerful but often insufficient. Economic relationships are rarely driven by a single factor. The <strong>multiple regression model</strong> allows us to quantify the relationship between a dependent variable and <em>several</em> independent variables simultaneously, which is crucial for tackling omitted variable bias.</p>
<section id="the-trivariate-model-interpretation" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="the-trivariate-model-interpretation"><span class="header-section-number">3.1</span> The Trivariate Model &amp; Interpretation</h2>
<p>The population multiple regression model with two explanatory variables (the trivariate model) is written as:</p>
<p><span class="math display">\[Y_i = \alpha + \beta_1 X_{1i} + \beta_2 X_{2i} + u_i\]</span></p>
<p>Taking expectations on both sides gives the conditional mean function:</p>
<p><span class="math display">\[E(Y_i | X_{1i}, X_{2i}) = \alpha + \beta_1 X_{1i} + \beta_2 X_{2i}\]</span></p>
<p>The key advantage of multiple regression is the <strong>ceteris paribus</strong> (all else equal) interpretation of its coefficients.</p>
<ul>
<li><span class="math inline">\(\beta_1\)</span> is the marginal effect of <span class="math inline">\(X_1\)</span> on <span class="math inline">\(Y\)</span>. It is the effect of a small change in the <span class="math inline">\(X_1\)</span> on the dependent variable, <strong>while holding <span class="math inline">\(X_2\)</span> constant</strong>.</li>
<li><span class="math inline">\(\beta_2\)</span> is the marginal effect of <span class="math inline">\(X_2\)</span> on <span class="math inline">\(Y\)</span>, <strong>while holding <span class="math inline">\(X_1\)</span> constant</strong>.</li>
</ul>
<p>This holding-constant effect is what helps isolate the direct effect of one variable, controlling for the influence of others.</p>
</section>
<section id="the-ols-estimators-and-normal-equations" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="the-ols-estimators-and-normal-equations"><span class="header-section-number">3.2</span> The OLS Estimators and Normal Equations</h2>
<p>The sample regression function (SRF) is:</p>
<p><span class="math display">\[\hat{Y}_i = \hat{\alpha} + \hat{\beta}_1 X_{1i} + \hat{\beta}_2 X_{2i}\]</span> <span class="math display">\[Y_i = \hat{\alpha} + \hat{\beta}_1 X_{1i} + \hat{\beta}_2 X_{2i} + \hat{u}_i\]</span></p>
<p>As in the bivariate case, the OLS procedure consists of choosing the unknown parameters <span class="math inline">\((\hat{\alpha}, \hat{\beta}_1, \hat{\beta}_2)\)</span> such that the residual sum of squares (SSR) is minimized:</p>
<p><span class="math display">\[\min_{\hat{\alpha}, \hat{\beta}_1, \hat{\beta}_2} \sum_{i=1}^n \hat{u}_i^2 = \min_{\hat{\alpha}, \hat{\beta}_1, \hat{\beta}_2} \sum_{i=1}^n (Y_i - \hat{\alpha} - \hat{\beta}_1 X_{1i} - \hat{\beta}_2 X_{2i})^2\]</span></p>
<p>Differentiating and setting the derivatives to zero yields the system of <strong>normal equations</strong>:</p>
<p><span class="math display">\[\begin{aligned}
\sum Y_i &amp;= n\hat{\alpha} + \hat{\beta}_1 \sum X_{1i} + \hat{\beta}_2 \sum X_{2i} \\
\sum X_{1i}Y_i &amp;= \hat{\alpha} \sum X_{1i} + \hat{\beta}_1 \sum X_{1i}^2 + \hat{\beta}_2 \sum X_{1i}X_{2i} \\
\sum X_{2i}Y_i &amp;= \hat{\alpha} \sum X_{2i} + \hat{\beta}_1 \sum X_{1i}X_{2i} + \hat{\beta}_2 \sum X_{2i}^2
\end{aligned}\]</span></p>
<p>Solving this system of three equations provides the formulas for the OLS estimators <span class="math inline">\(\hat{\alpha}\)</span>, <span class="math inline">\(\hat{\beta}_1\)</span>, and <span class="math inline">\(\hat{\beta}_2\)</span>. While the formulas are more complex than in the simple regression case, the intuition is similar.</p>
<p>Hence, the OLS estimators for the slope coefficients in a multiple regression model <span class="math inline">\(Y_i = \alpha + \beta_1 X_{1i} + \beta_2 X_{2i} + u_i\)</span> are given by:</p>
<p><span class="math display">\[
\begin{align*}
\hat{\beta}_1&amp;=\frac{(\sum_{i=1}^n x_{1i}y_i)(\sum_{i=1}^n x_{2i}^2)-(\sum_{i=1}^n x_{2i}y_i)(\sum_{i=1}^n x_{1i}x_{2i})}{(\sum_{i=1}^n x_{1i}^2)(\sum_{i=1}^n x_{2i}^2)-(\sum_{i=1}^n x_{1i}x_{2i})^2}\\
\hat{\beta}_2&amp;=\frac{(\sum_{i=1}^n x_{2i}y_i)(\sum_{i=1}^n x_{1i}^2)-(\sum_{i=1}^n x_{1i}y_i)(\sum_{i=1}^n x_{1i}x_{2i})}{(\sum_{i=1}^n x_{1i}^2)(\sum_{i=1}^n x_{2i}^2)-(\sum_{i=1}^n x_{1i}x_{2i})^2}
\end{align*}
\]</span> And the estimator for the intercept is:</p>
<p><span class="math display">\[
\hat\alpha = \bar Y - \hat\beta_1 \bar X_1 - \hat\beta_2 \bar X_2
\]</span></p>
<section id="extending-the-mtcars-model" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="extending-the-mtcars-model"><span class="header-section-number">3.2.1</span> Extending the <code>mtcars</code> Model</h3>
<p>We can estimate the coefficients easily using R. Let’s first expand our car mileage model. Perhaps a car’s horsepower (<code>hp</code>) also affects its fuel efficiency (<code>mpg</code>), in addition to its weight (<code>wt</code>). We can estimate this trivariate model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate a multiple regression model</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># mpg = alpha + beta1 * wt + beta2 * hp + u</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>multi_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> hp, <span class="at">data =</span> mtcars)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary results</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multi_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt + hp, data = mtcars)

Residuals:
   Min     1Q Median     3Q    Max 
-3.941 -1.600 -0.182  1.050  5.854 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 37.22727    1.59879  23.285  &lt; 2e-16 ***
wt          -3.87783    0.63273  -6.129 1.12e-06 ***
hp          -0.03177    0.00903  -3.519  0.00145 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.593 on 29 degrees of freedom
Multiple R-squared:  0.8268,    Adjusted R-squared:  0.8148 
F-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12</code></pre>
</div>
</div>
<p><strong>Interpretation of the Coefficients:</strong></p>
<ul>
<li><strong>wt coefficient (-3.878):</strong> Holding horsepower constant, a one-ton increase in weight is associated with a decrease in fuel efficiency of approximately 3.88 miles per gallon, on average.</li>
<li><strong>hp coefficient (-0.032):</strong> Holding weight constant, a one-horsepower increase is associated with a decrease in fuel efficiency of approximately 0.032 miles per gallon, on average.</li>
<li><strong>Intercept (37.227):</strong> The predicted miles per gallon for a car that weighs 0 tons and has 0 horsepower. (Note: This is often not a meaningful value and serves just as a baseline for the regression line.)</li>
</ul>
<p>Notice how the coefficient on <code>wt</code> changed from -5.34 in the simple regression to -3.88 in this multiple regression. This suggests that horsepower was an omitted variable that was correlated with both weight and mileage, and failing to control for it biased our initial estimate of the effect of weight.</p>
</section>
</section>
<section id="standard-errors-of-the-ols-estimates" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="standard-errors-of-the-ols-estimates"><span class="header-section-number">3.3</span> Standard Errors of the OLS Estimates</h2>
<p>The formula for the variance of a slope estimator, say <span class="math inline">\(\hat{\beta}_1\)</span>, in the trivariate model is:</p>
<p><span class="math display">\[Var(\hat{\beta}_1) = \frac{\sigma^2}{\sum (X_{1i} - \bar{X}_1)^2 (1 - r^2_{12})}\]</span></p>
<ul>
<li><span class="math inline">\(\sigma^2\)</span> is the variance of the error term <span class="math inline">\(u_i\)</span>.</li>
<li><span class="math inline">\(\sum (X_{1i} - \bar{X}_1)^2\)</span> is the total variation in <span class="math inline">\(X_1\)</span>.</li>
<li><span class="math inline">\(r_{12}\)</span> is the sample correlation between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>.</li>
</ul>
<p>Since we never observe the true error variance (<span class="math inline">\(\sigma^2\)</span>), we bootstrap and use its estimate:</p>
<p><span class="math display">\[\hat{\sigma}^2 = \frac{1}{n - k} \sum_{i=1}^n \hat{u}_i^2\]</span></p>
<p>where <span class="math inline">\(k\)</span> is the number of estimated coefficients (including the constant, so <span class="math inline">\(k=3\)</span> for our model). The standard error of the coefficient is then the square root of its estimated variance: <span class="math inline">\(SE(\hat{\beta}_1) = \sqrt{\widehat{Var}(\hat{\beta}_1)}\)</span>.</p>
<p>Hence, the standard errors for <span class="math inline">\(\beta 's\)</span> in the model <span class="math inline">\(Y_i = \alpha + \beta_1 X_{1i} + \beta_2 X_{2i} + u_i\)</span> are given by:</p>
<p><span class="math display">\[
\begin{aligned}
SE(\hat{\beta}_1) &amp;= \sqrt{\widehat{Var}(\hat{\beta}_1)} \quad  \text{or} \quad \hat{\sigma} \frac{1}{\sqrt{\sum x_{1i}^2 (1 - r_{12}^2)}} \\
SE(\hat{\beta}_2) &amp;= \sqrt{\widehat{Var}(\hat{\beta}_2)} \text{or} \quad \hat{\sigma} \frac{1}{\sqrt{\sum x_{2i}^2 (1 - r_{12}^2)}}
\end{aligned}
\]</span></p>
<p>The standard error for the intercept is:</p>
<p><span class="math display">\[
SE(\hat{\alpha}) = \sqrt{\widehat{Var}(\hat{\alpha})} = \hat{\sigma} \sqrt{ \frac{1}{n} + \frac{\overline{X}_1^2 \sum x_{2i}^2 + \overline{X}_2^2 \sum x_{1i}^2 - 2\overline{X}_1 \overline{X}_2 \sum x_{1i} x_{2i}}{\sum x_{1i}^2 \sum x_{2i}^2 - (\sum x_{1i} x_{2i})^2} }
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\hat{\sigma} = \sqrt{\frac{\sum \hat{u}_i^2}{n - k}}\)</span> is the standard error of the regression (<span class="math inline">\(SER\)</span>),</li>
<li><span class="math inline">\(r_{12}\)</span> is the sample correlation between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>,</li>
<li><span class="math inline">\(x_{1i} = X_{1i} - \bar{X}_1\)</span> and <span class="math inline">\(x_{2i} = X_{2i} - \bar{X}_2\)</span> are deviations</li>
</ul>
<p>The <code>summary()</code> function in R displays these standard errors, as seen in the output above.</p>
</section>
<section id="r-squared-and-the-adjusted-r-squared" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="r-squared-and-the-adjusted-r-squared"><span class="header-section-number">3.4</span> R-squared and The Adjusted R-squared</h2>
<p>As in the bivariate case, the coefficient of determination, <span class="math inline">\(R^2\)</span>, is the fraction of the sample variation in <span class="math inline">\(Y\)</span> explained by the model:</p>
<p><span class="math display">\[R^2 = \frac{SSE}{SST} = 1 - \frac{SSR}{SST}\]</span></p>
<p>A key feature of multiple regression is that adding <em>any</em> new variable (even an irrelevant one) will never decrease the <span class="math inline">\(R^2\)</span>. Because of this, we often prefer the <strong>adjusted R-squared</strong>, which penalizes for adding irrelevant variables.</p>
<p><span class="math display">\[\bar{R}^2 = 1 - \frac{SSR/(n-k)}{SST/(n-1)} = 1 - \left( \frac{n-1}{n-k} \right) \frac{SSR}{SST}\]</span></p>
<ul>
<li><span class="math inline">\(n\)</span> is the sample size.</li>
<li><span class="math inline">\(k\)</span> is the number of coefficients, including the constant.</li>
<li><span class="math inline">\(\bar{R}^2\)</span> can decrease if a new variable adds little explanatory power, providing a better gauge of whether a variable should be included.</li>
<li>Always compare <span class="math inline">\(\bar{R}^2\)</span>, not <span class="math inline">\(R^2\)</span>, when models have a different number of predictors.</li>
</ul>
<p>In our <code>mtcars</code> output, we see both <code>R-squared:  0.8268</code> and <code>Adjusted R-squared:  0.8148</code>.</p>
<section id="interpreting-r2-and-barr2-in-practice" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="interpreting-r2-and-barr2-in-practice"><span class="header-section-number">3.4.1</span> Interpreting <span class="math inline">\(R^2\)</span> and <span class="math inline">\(\bar{R}^2\)</span> in Practice</h3>
<p>It is critical to remember that: 1. An increase in the <span class="math inline">\(R^2\)</span> or <span class="math inline">\(\bar{R}^2\)</span> does not necessarily mean that an added variable is statistically significant. 2. A high <span class="math inline">\(R^2\)</span> or <span class="math inline">\(\bar{R}^2\)</span> does not mean that the regressors are a true cause of the dependent variable (causation vs.&nbsp;correlation). 3. A high <span class="math inline">\(R^2\)</span> or <span class="math inline">\(\bar{R}^2\)</span> does not mean that there is no omitted variable bias. 4. A high <span class="math inline">\(R^2\)</span> or <span class="math inline">\(\bar{R}^2\)</span> does not necessarily mean that you have the most appropriate set of regressors, nor does a low <span class="math inline">\(R^2\)</span> or <span class="math inline">\(\bar{R}^2\)</span> mean that you have an inappropriate model.</p>
</section>
</section>
<section id="hypothesis-testing" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="hypothesis-testing"><span class="header-section-number">3.5</span> Hypothesis Testing</h2>
<section id="testing-individual-coefficients" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="testing-individual-coefficients"><span class="header-section-number">3.5.1</span> Testing Individual Coefficients</h3>
<p>The procedure for testing hypotheses about a single coefficient is identical to the simple regression case. For example, to test if <span class="math inline">\(X_1\)</span> has a significant effect on <span class="math inline">\(Y\)</span> after controlling for <span class="math inline">\(X_2\)</span>:</p>
<ul>
<li><span class="math inline">\(H_0: \beta_1 = 0\)</span></li>
<li><span class="math inline">\(H_1: \beta_1 \neq 0\)</span></li>
</ul>
<p>The test statistic is the t-ratio: <span class="math inline">\(t = \displaystyle\frac{\hat{\beta}_1}{SE(\hat{\beta}_1)}\)</span>.</p>
<p>As a rule of thumb, we reject the null hypothesis if the absolute value of the t-ratio is greater than “2”.</p>
</section>
<section id="testing-the-overall-significance-the-f-test" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="testing-the-overall-significance-the-f-test"><span class="header-section-number">3.5.2</span> Testing the Overall Significance: The F-Test</h3>
<p>The test for the overall significance of the regression is a joint test that all slope coefficients are equal to zero:</p>
<p><span class="math display">\[
H_0: \beta_1 = \beta_2 = 0 \quad \text{vs.} \quad H_1: \text{at least one } \beta_j \neq 0
\]</span></p>
<p>This test is conducted using the <strong>F-statistic</strong>. The F-statistic can be computed in several equivalent forms:</p>
<p><strong>1. Using sums of squares and cross-products:</strong> <span class="math display">\[
F = \frac{ \left( \hat{\beta}_1 \sum y_i x_{1i} + \hat{\beta}_2 \sum y_i x_{2i} \right) / m }{ \sum \hat{u}_i^2 / (n - k) }
\]</span> where</p>
<ul>
<li><span class="math inline">\(m\)</span> is the number of restrictions</li>
<li><span class="math inline">\(n-k\)</span> is the degree of freedom of the regression</li>
</ul>
<p>The above is the ratio of explained and unexplained sums of squares divided by their respective degrees of freedom which corresponds to ANOVA:</p>
<p><span class="math display">\[
F = \frac{SSE / (k - 1)}{SSR / (n - k)}
\]</span> where <span class="math inline">\(k\)</span> is the total number of estimated parameters (for a model with two regressors, <span class="math inline">\(k=3\)</span>: <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\beta_2\)</span>).</p>
<p>Note this is the same if we use the coefficient of determination (<span class="math inline">\(R^2\)</span>):</p>
<p><span class="math display">\[
F = \frac{R^2 / (k - 1)}{(1 - R^2) / (n - k)}
\]</span></p>
<p>Hence, the new test in multiple regression is the test for <strong>overall significance of the regression</strong>, which is a joint test that all slope coefficients are simultaneously equal to zero.</p>
<ul>
<li><span class="math inline">\(H_0: \beta_1 = \beta_2 = 0\)</span></li>
<li><span class="math inline">\(H_1: \text{At least one } \beta_j \neq 0\)</span></li>
</ul>
<p>This test is given by the <strong>F-statistic</strong>, which is reported in the standard regression output. The F-statistic is constructed using the sums of squares from the ANOVA (Analysis of Variance) framework:</p>
<p><span class="math display">\[SST = SSE + SSR\]</span></p>
<p>The F-statistic is the ratio of the explained to unexplained variance, adjusted for degrees of freedom:</p>
<p><span class="math display">\[F = \frac{SSE / (k-1)}{SSR / (n-k)} = \frac{MSR}{MSE}\]</span></p>
<p>where <span class="math inline">\(k-1\)</span> is the number of slope coefficients. A large F-statistic provides evidence against the null hypothesis that the model provides no better fit than a model with only an intercept.</p>
</section>
<section id="joint-tests-and-restricted-models" class="level3" data-number="3.5.3">
<h3 data-number="3.5.3" class="anchored" data-anchor-id="joint-tests-and-restricted-models"><span class="header-section-number">3.5.3</span> Joint Tests and Restricted Models</h3>
<p>The F-test can be generalized to test any set of <strong>linear restrictions</strong>. For example, we can test if a subset of coefficients is equal to zero.</p>
<p>Assume the <strong>unrestricted model</strong> is:</p>
<p><span class="math display">\[Y_i = \alpha + \beta_1 X_{1i} + \beta_2 X_{2i} + \beta_3 X_{3i} + u_i\]</span></p>
<p>We could test the joint hypothesis:</p>
<ul>
<li><span class="math inline">\(H_0: \beta_2 = 0, \beta_3 = 0\)</span></li>
<li><span class="math inline">\(H_1: H_0 \text{ is not true}\)</span></li>
</ul>
<p>This involves estimating a <strong>restricted model</strong> where the restrictions under the null are imposed: <span class="math display">\[Y_i = \alpha + \beta_1 X_{1i} + u_i\]</span></p>
<p>The general F-statistic formula for testing <span class="math inline">\(m\)</span> restrictions is:</p>
<p><span class="math display">\[F = \frac{(SSR_r - SSR_{ur}) / m}{SSR_{ur} / (n - k)}\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(SSR_r\)</span> is the sum of squared residuals from the restricted model.</li>
<li><span class="math inline">\(SSR_{ur}\)</span> is the sum of squared residuals from the unrestricted model.</li>
<li><span class="math inline">\(m\)</span> is the number of restrictions.</li>
<li><span class="math inline">\(n - k\)</span> is the degrees of freedom in the unrestricted model.</li>
</ul>
<p>Here is another example where We could test the joint hypothesis:</p>
<ul>
<li><span class="math inline">\(H_0: \beta_1 = 0, \beta_2 + \beta_3 = 1\)</span></li>
<li><span class="math inline">\(H_1: H_0 \text{ is not true}\)</span></li>
</ul>
<p>Here, the unrestricted model is the same as before:</p>
<p><span class="math display">\[Y_i = \alpha + \beta_1 X_{1i} + \beta_2 X_{2i} + \beta_3 X_{3i} + u_i\]</span></p>
<p>To find the restricted model, we impose the null hypothesis:</p>
<p>Substitute <span class="math inline">\(\beta_1 = 0\)</span> and <span class="math inline">\(\beta_3 = 1 - \beta_2\)</span> into the model:</p>
<p><span class="math display">\[Y_i = \alpha + \beta_2 X_{2i} + (1 - \beta_2) X_{3i} + u_i\]</span></p>
<p>Rearrange the equation:</p>
<p><span class="math display">\[Y_i = \alpha + X_{3i} + \beta_2 (X_{2i} - X_{3i}) + u_i\]</span></p>
<p>Define a new dependent variable <span class="math inline">\(Y_i^* = Y_i - X_{3i}\)</span>:</p>
<p><span class="math display">\[Y_i^* = \alpha + \beta_2 (X_{2i} - X_{3i}) + u_i\]</span></p>
<p>We then perform the F-test as usual and a low p-value would lead to a rejection of the null hypothesis <span class="math inline">\(H_0\)</span>. Note here that <span class="math inline">\(m\)</span> the number of restrictions is 2 and not 3!</p>
</section>
</section>
<section id="the-problem-of-omitted-variable-bias" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="the-problem-of-omitted-variable-bias"><span class="header-section-number">3.6</span> The Problem of Omitted Variable Bias</h2>
<p>Often, we are interested in understanding the relation between two variables (<span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>). But running a simple regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span> might not be enough. The assumption <span class="math inline">\(Cov(X, u)=0\)</span> might be violated if the error term <span class="math inline">\(u\)</span> contains a variable that is correlated with <span class="math inline">\(X\)</span>, thereby introducing a bias. Multiple regression is a primary tool to help resolve this <strong>endogeneity</strong> problem.</p>
<section id="direction-of-the-bias" class="level3" data-number="3.6.1">
<h3 data-number="3.6.1" class="anchored" data-anchor-id="direction-of-the-bias"><span class="header-section-number">3.6.1</span> Direction of the Bias</h3>
<p>Omitting an important variable introduces a bias to the OLS estimator. The direction of this bias can be formalized.</p>
<p>Suppose the <strong>true model</strong> is: <span class="math display">\[Y_i = \alpha + \beta_1 X_{1i} + \beta_2 X_{2i} + u_i\]</span> But we incorrectly estimate the <strong>misspecified model</strong>: <span class="math display">\[Y_i = \alpha + \beta_1 X_{1i} + v_i \quad \text{where} \quad v_i = \beta_2 X_{2i} + u_i\]</span></p>
<p>The bias in the simple regression estimator <span class="math inline">\(\tilde{\beta}_1\)</span> is: <span class="math display">\[Bias(\tilde{\beta}_1) = E[\tilde{\beta}_1] - \beta_1 = \beta_2 \cdot \tilde{\delta}_1\]</span></p>
<p>where <span class="math inline">\(\tilde{\delta}_1\)</span> is the slope coefficient from an <strong>auxiliary regression</strong> of the omitted variable (<span class="math inline">\(X_2\)</span>) on the included variable (<span class="math inline">\(X_1\)</span>): <span class="math display">\[X_{2i} = \delta_0 + \delta_1 X_{1i} + e_i\]</span></p>
<ul>
<li>The <strong>sign of the bias</strong> depends on the signs of <span class="math inline">\(\beta_2\)</span> (the effect of the omitted variable on <span class="math inline">\(Y\)</span>) and <span class="math inline">\(\tilde{\delta}_1\)</span> (the correlation between <span class="math inline">\(X_2\)</span> and <span class="math inline">\(X_1\)</span>).</li>
<li>The <strong>size of the bias</strong> depends on the magnitude of <span class="math inline">\(\beta_2\)</span> and <span class="math inline">\(\tilde{\delta}_1\)</span>.</li>
</ul>
</section>
</section>
<section id="the-cost-of-including-an-irrelevant-variable" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="the-cost-of-including-an-irrelevant-variable"><span class="header-section-number">3.7</span> The Cost of Including an Irrelevant Variable</h2>
<p>Conversely, including a variable that does not belong in the true model (i.e., whose true coefficient is zero) has different consequences.</p>
<p>Suppose the <strong>true model</strong> is: <span class="math display">\[Y_i = \alpha + \beta_1 X_{1i} + u_i\]</span> But we incorrectly estimate: <span class="math display">\[Y_i = \alpha + \beta_1 X_{1i} + \beta_2 X_{2i} + v_i\]</span></p>
<ul>
<li><strong>Does it introduce bias?</strong> No.&nbsp;The OLS estimators for all coefficients, including <span class="math inline">\(\hat{\beta}_1\)</span>, remain <strong>unbiased</strong>.</li>
<li><strong>What is the cost?</strong> <strong>Increased variance.</strong> The estimates become less precise. The standard error of <span class="math inline">\(\hat{\beta}_1\)</span> will generally be larger than it would be in the correctly specified simple regression model, leading to less powerful hypothesis tests and wider confidence intervals.</li>
</ul>
<p>The trade-off is clear: omitting a relevant variable causes bias, while including an irrelevant variable reduces efficiency. When in doubt, it is often less harmful to include a potentially irrelevant variable than to omit a potentially relevant one.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./assumptions.html" class="pagination-link" aria-label="The Classical Linear Model (Gauss-Markov) Assumptions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Classical Linear Model (Gauss-Markov) Assumptions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>